apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: showks-portal-frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/cloudnativedaysjp/showks-manifests-stg.git
    targetRevision: HEAD
    path: manifests/showks-portal-frontend
  syncPolicy:
    automated: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: showks
